language: java
jdk:
  - oraclejdk8
  
sudo: false

before_script:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo npm install -g bower

notifications:
  slack: fablabs-ch:ViuClvLZOVFlDASnZCPC1vId
