language: java
jdk:
  - oraclejdk8

sudo: required

env:
  global:
    - TAG: develop
    - IMAGE_NAME: gaetancollaud/fablab-manager

services:
  - docker

script:
  - mvn clean install
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $IMAGE_NAME:TAG .
  - docker push $IMAGE_NAME:TAG
  - if [[ "$TRAVIS_TAG" != "" ]]; then docker tag $IMAGE_NAME:TAG $IMAGE_NAME:latest && docker push $IMAGE_NAME:latest; fi

