language: java
jdk:
  - oraclejdk8

sudo: required

env:
  global:
    - TAG: develop
    - IMAGE_NAME: gaetancollaud/fablab-manager

services:
  - docker

script:
  - mvn clean install
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t gaetancollaud/fablab-manager:$TRAVIS_BRANCH .
  - docker push gaetancollaud/fablab-manager:$TRAVIS_BRANCH
  - if [[ "$TRAVIS_TAG" != "" ]]; then docker tag gaetancollaud/fablab-manager:$TRAVIS_BRANCH gaetancollaud/fablab-manager:latest && docker push gaetancollaud/fablab-manager:latest; fi

