language: java
jdk:
  - oraclejdk8

sudo: required

env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.4.2
    - TAG: develop
    - IMAGE_NAME: gaetancollaud/fablab-manager

services:
  - docker

script:
  - mvn clean install

after_success:
  - docker build -t $IMAGE_NAME:$TAG .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $IMAGE_NAME:$TAG
