version: '2'
services:
  mysql:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=fablab
     - MYSQL_DATABASE=fablab
     - MYSQL_USER=fablab
     - MYSQL_PASSWORD=fablab
  web:
    image: gaetancollaud/fablab-manager
    ports:
     - "8080:8080"
    links:
     - mysql
